{% set version = "1.2.15" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-genenet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/GeneNet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/GeneNet/GeneNet_{{ version }}.tar.gz
  sha256: 555ac4e1d6c53c099b94b9298b6a8893a07797886a21ce3655a98fa9a1326a85

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-corpcor >=1.6.8
    - r-fdrtool >=1.2.15
    - r-longitudinal >=1.1.12
  run:
    - r-base
    - r-corpcor >=1.6.8
    - r-fdrtool >=1.2.15
    - r-longitudinal >=1.1.12

test:
  commands:
    - $R -e "library('GeneNet')"           # [not win]
    - "\"%R%\" -e \"library('GeneNet')\""  # [win]

about:
  home: http://strimmerlab.org/software/genenet/
  license: GPL-3.0-or-later
  summary: 'Analyzes gene expression (time series) data with focus on the inference of gene networks. In particular, GeneNet implements the methods of Schaefer and  Strimmer (2005a,b,c) and Opgen-Rhein and Strimmer (2006, 2007) for learning large-scale gene association networks (including assignment of putative directions).  '
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
