appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: de9Fg2zcYXmLO9ljD9tshy7+OZLK++wgbL4wZgIuXpLKTcTnXXwUN0D5jm8cXMbGv4a1XZv1VRtisIkEVYDr+rLxJHl/IAMqkGufCLum03VkhQwWhNeUqyHGN7FklO92kx9VE8HSVlJ/X8InucB109CCzSBDtp4TiAObySv+4jYS1P707xwkxA4v/U2sPxCwpfbtebh46HKll3qVSilcv2GGNemGLCrZH0fWioLbOhqn2vSH84UJHiHaxmrCyjCSROh36fM0A4sfkD5ZRovkltJvdHo+xJDl49es7RSnLLx8BjNIF5YCwDxxrZBSQM5OC4Ad17kx3FmrfrOJJ9Bkbq5GdCbwAkdrDIeQGPCB+11ILsh7Y5wSz+i9bLIUniUiBOguzsgigZXw40f5mxDKlA+zyfIPcJo5vzle91Sh9Fh5WZwGMQ/uRbWlt+IFvsw1XmPNxSXzFkHBuEb/Yx7ZW2Bh5NZKXYBiB4AZGpotrljLZyQ3FX1uwF+AmpnU29Co0xRxn+NhQmptyyVguPWuHVl0bcPrRPwN4PzYyW0FKZSroeac847Z8TxEKHGN66KpO6pNwGR4oFl1VGmq9B5d5n7KCEyRpWNqU67dgzCDCKh5gnR3DnXsfwAbZ91Opv4SlwQNRlm2tblfSXV3TuHRqAl6W3qVMaKRX7j3gNkWsyI=
